# Generated by Django 6.1.1 on 2026-09-26 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(default='Admin', max_length=100)),
                ('created_at', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CalmStacks 24-Hour Hackathon 2026', max_length=255)),
                ('event_type', models.CharField(blank=True, default='Hackathon', max_length=100)),
                ('edition', models.CharField(blank=True, default='Season 1, 2026', max_length=100)),
                ('start_date', models.CharField(blank=True, default='2026-09-25', max_length=50)),
                ('end_date', models.CharField(blank=True, default='2026-09-26', max_length=50)),
                ('venue', models.CharField(blank=True, default='Malnad College of Engineering, Hassan', max_length=255)),
                ('organizer', models.CharField(blank=True, default='Dept. of CSE, MCE Hassan // In collaboration with CalmStacks', max_length=255)),
                ('description', models.TextField(blank=True, default='Official 24-Hour Hackathon organized by Dept. of Computer Science & Engineering, Malnad College of Engineering, Hassan.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('registered_at', models.CharField(blank=True, max_length=100)),
                ('team_name', models.CharField(max_length=255)),
                ('team_size', models.CharField(blank=True, max_length=100)),
                ('lead_name', models.CharField(max_length=255)),
                ('usn', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=100)),
                ('member2', models.CharField(blank=True, max_length=255)),
                ('usn2', models.CharField(blank=True, max_length=100)),
                ('member3', models.CharField(blank=True, max_length=255)),
                ('usn3', models.CharField(blank=True, max_length=100)),
                ('member4', models.CharField(blank=True, max_length=255)),
                ('usn4', models.CharField(blank=True, max_length=100)),
                ('payment_status', models.CharField(blank=True, default='PENDING', max_length=50)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('utr', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('role', models.CharField(default='Member', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('usn', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('registered_at', models.CharField(blank=True, max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='hackathon.team')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
